POST http://127.0.0.1:3001/account/singout/ HTTP/1.1
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGZhYjlhNWE5MTcyYzI3OTQxY2FlM2IiLCJpYXQiOjE2MjcwNTYzMTB9.26BAYvDxIgm3h0MpwyKKl5Xrbo38_TImM1fPUyy649k"
}